S4 us10/feat admindashboard
WildCodeSchool/2023-09-JS-Toulouse-666-Geocode pull request #29
Opened 2024-01-25 14:25 UTC by marcDjango

2024-01-25 14:59 UTC, QuentinVay approved these changes

2024-01-25 16:09 UTC, ArthurHtbk requested changes

2024-01-25 16:09 UTC, ArthurHtbk commented on frontend/src/components/admin/table/tableur.scss
> +          //   background-color: rgba(209, 181, 103, 0.1);
😱

2024-01-25 16:09 UTC, ArthurHtbk commented on frontend/src/layout/AdminLayout.scss
> +          // background: yellow;
😱

2024-01-26 08:43 UTC, ArthurHtbk approved these changes

2024-01-26 08:43 UTC, merged